### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by truls** [Stypox/arg-parser#2]
You haven't provided any license information for arg-parser. This means that currently "All rights reserved" applies which makes it impossible to include in another project.

**Comment by ste-phil** [comment]
Would appreciate a license as well

**Comment by Stypox** [comment]
Done in de0561f9c4eaccb795f98e64d74ced57ab94a30c
I don't know why I didn't see any notification for this thread, sorry for answering so late ;-)
@truls @xXPancakeXx
